# Default initial positions for rh_plus_7_axis_robot_arm's ros2_control fake system

initial_positions:
  joint1: 0.0
  joint2: 0.0
  joint3: 0.0
  joint4: 0.0
  joint5: 0.0
  joint6: 0.0
  jointf1: 0.0
  jointf2: 0.0