controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joint_names:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
      command_interfaces:
        - position
      state_interfaces:
        - position
      allow_nonzero_velocity_at_trajectory_end: true

    gripper_controller:
      type: position_controllers/GripperActionController
      joint_names:
        - jointf1
        - jointf2

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster