controller_manager:
  ros__parameters:
    update_rate: 100

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 50

arm_controller:
  ros__parameters:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    state_publish_rate: 50
    action_monitor_rate: 30
    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.01
      joint1:
        trajectory: 0.1
        goal: 0.1
      joint2:
        trajectory: 0.1
        goal: 0.1
      joint3:
        trajectory: 0.1
        goal: 0.1
      joint4:
        trajectory: 0.1
        goal: 0.1
      joint5:
        trajectory: 0.1
        goal: 0.1
      joint6:
        trajectory: 0.1
        goal: 0.1
    gains:
      joint1: {p: 100.0, d: 1.0, i: 0.0, i_clamp: 0.0}
      joint2: {p: 100.0, d: 1.0, i: 0.0, i_clamp: 0.0}
      joint3: {p: 100.0, d: 1.0, i: 0.0, i_clamp: 0.0}
      joint4: {p: 100.0, d: 1.0, i: 0.0, i_clamp: 0.0}
      joint5: {p: 100.0, d: 1.0, i: 0.0, i_clamp: 0.0}
      joint6: {p: 100.0, d: 1.0, i: 0.0, i_clamp: 0.0}
